[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.optimized]
via_ir = true

[rpc_endpoints]
arb1 = "https://arb1.arbitrum.io/rpc"
arbgoerli = "https://goerli-rollup.arbitrum.io/rpc"
arbnova = "https://nova.arbitrum.io/rpc"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config